spring:
  datasource:
    url: jdbc:mysql://${HOST:localhost}:${PORT:3306}/${DB_NAME:userTestTask}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
